import os
from dragondrop.get_domain_from_url import getDomain

def populate():

    #Users
    James = User.objects.create_user('James',None, 'Jamespassword')
    James.save()
    Gosel = User.objects.create_user('Gosel',None, 'Goselpassword')
    Gosel.save()
    Jean = User.objects.create_user('Jean',None, 'Jeanpassword')
    Jean.save()
    Wen = User.objects.create_user('Wen',None, 'Wenpassword')
    Wen.save()
    Martyna = User.objects.create_user('Martyna',None, 'Martynapassword')
    Martyna.save()

    #Folders
    f_Misc_Trees_and_Graphs_Wen = add_folder(foldername='Misc Trees and Graphs',fusername_fk=Wen)
    f_bin_Jean = add_folder(foldername='bin',fusername_fk=Jean)
    f_Bar_Chart_Gosel = add_folder(foldername='Bar Chart',fusername_fk=Gosel)
    f_Online_Editors_Jean = add_folder(foldername='Online Editors',fusername_fk=Jean)
    f_Misc_Charts_Jean = add_folder(foldername='Misc Charts',fusername_fk=Jean)
    f_Online_Editors_Martyna = add_folder(foldername='Online Editors',fusername_fk=Martyna)
    f_Sunburst_and_Partition_layout_Wen = add_folder(foldername='Sunburst and Partition layout',fusername_fk=Wen)
    f_Evaluation_Gosel = add_folder(foldername='Evaluation',fusername_fk=Gosel)
    f_Useful_snippets_Jean = add_folder(foldername='Useful snippets',fusername_fk=Jean)
    f_Miscellaneous_visualizations_Gosel = add_folder(foldername='Miscellaneous visualizations',fusername_fk=Gosel)
    f_Parallel_Coordinates_Parallel_sets_and_Sankey_Gosel = add_folder(foldername='Parallel Coordinates Parallel sets and Sankey',fusername_fk=Gosel)
    f_Tree_Wen = add_folder(foldername='Tree',fusername_fk=Wen)
    f_Jason_Davies_James = add_folder(foldername='Jason Davies',fusername_fk=James)
    f_Products_Martyna = add_folder(foldername='Products',fusername_fk=Martyna)
    f_Maps_Jean = add_folder(foldername='Maps',fusername_fk=Jean)
    f_bin_James = add_folder(foldername='bin',fusername_fk=James)
    f_Chord_Layout_Jean = add_folder(foldername='Chord Layout',fusername_fk=Jean)
    f_Histogram_Gosel = add_folder(foldername='Histogram',fusername_fk=Gosel)
    f_Scatterplot_and_Bubble_chart_Gosel = add_folder(foldername='Scatterplot and Bubble chart',fusername_fk=Gosel)
    f_Maps_Gosel = add_folder(foldername='Maps',fusername_fk=Gosel)
    f_Store_Apps_Martyna = add_folder(foldername='Store Apps',fusername_fk=Martyna)
    f_Force_Layout_Wen = add_folder(foldername='Force Layout',fusername_fk=Wen)
    f_Libraries_Martyna = add_folder(foldername='Libraries',fusername_fk=Martyna)
    f_Parallel_Coordinates_Parallel_sets_and_Sankey_Wen = add_folder(foldername='Parallel Coordinates Parallel sets and Sankey',fusername_fk=Wen)
    f_Institute_for_Health_Metrics_and_Evaluation_Gosel = add_folder(foldername='Institute for Health Metrics and Evaluation',fusername_fk=Gosel)
    f_Jim_Vallandingham_James = add_folder(foldername='Jim Vallandingham',fusername_fk=James)
    f_Line_and_Area_Chart_Gosel = add_folder(foldername='Line and Area Chart',fusername_fk=Gosel)
    f_Jerome_Cukier_Martyna = add_folder(foldername='Jerome Cukier',fusername_fk=Martyna)
    f_bin_Wen = add_folder(foldername='bin',fusername_fk=Wen)
    f_Chord_Layout_Wen = add_folder(foldername='Chord Layout',fusername_fk=Wen)
    f_Pie_Chart_Gosel = add_folder(foldername='Pie Chart',fusername_fk=Gosel)
    f_Jason_Davies_Martyna = add_folder(foldername='Jason Davies',fusername_fk=Martyna)
    f_Interoperability_Jean = add_folder(foldername='Interoperability',fusername_fk=Jean)
    f_Miscellaneous_visualizations_Jean = add_folder(foldername='Miscellaneous visualizations',fusername_fk=Jean)

    #Bookmarks
    bmID_317,bmID_b_317 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/animated-trig/')
    bmID_317.save()
    bmID_317.fname.add(f_Jason_Davies_James)
    bmID_147,bmID_b_147 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1256572')
    bmID_147.save()
    bmID_147.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_271,bmID_b_271 = Bookmark.objects.get_or_create(url='http://www.jeromecukier.net/projects/models/nuitblanche.html')
    bmID_271.save()
    bmID_271.fname.add(f_Jerome_Cukier_Martyna)
    bmID_140,bmID_b_140 = Bookmark.objects.get_or_create(url='http://ggruiz.me/explosions/')
    bmID_140.save()
    bmID_140.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_185,bmID_b_185 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/3689677')
    bmID_185.save()
    bmID_185.fname.add(f_Useful_snippets_Jean)
    bmID_72,bmID_b_72 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1080941')
    bmID_72.save()
    bmID_72.fname.add(f_Force_Layout_Wen)
    bmID_223,bmID_b_223 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2759731')
    bmID_223.save()
    bmID_223.fname.add(f_Interoperability_Jean)
    bmID_59,bmID_b_59 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/910126')
    bmID_59.save()
    bmID_59.fname.add(f_Sunburst_and_Partition_layout_Wen)
    bmID_124,bmID_b_124 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2011590')
    bmID_124.save()
    bmID_124.fname.add(f_Misc_Charts_Jean)
    bmID_265,bmID_b_265 = Bookmark.objects.get_or_create(url='https://github.com/vogievetsky/DVL')
    bmID_265.save()
    bmID_265.fname.add(f_Libraries_Martyna)
    bmID_296,bmID_b_296 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/graph-music/')
    bmID_296.save()
    bmID_296.fname.add(f_Jason_Davies_James)
    bmID_115,bmID_b_115 = Bookmark.objects.get_or_create(url='http://www.rjbaxley.com/p/publications.html')
    bmID_115.save()
    bmID_115.fname.add(f_Chord_Layout_Jean)
    bmID_103,bmID_b_103 = Bookmark.objects.get_or_create(url='http://www.nu.nl/files/datajournalistiek/ek/ek2012.htm#.UKJ5yuOe8ww')
    bmID_103.save()
    bmID_103.fname.add(f_Chord_Layout_Wen)
    bmID_117,bmID_b_117 = Bookmark.objects.get_or_create(url='http://redotheweb.com/DependencyWheel/')
    bmID_117.save()
    bmID_117.fname.add(f_Chord_Layout_Jean)
    bmID_170,bmID_b_170 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/d/2361485/')
    bmID_170.save()
    bmID_170.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_286,bmID_b_286 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/primos/')
    bmID_286.save()
    bmID_286.fname.add(f_Jason_Davies_Martyna)
    bmID_146,bmID_b_146 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1098617')
    bmID_146.save()
    bmID_146.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_139,bmID_b_139 = Bookmark.objects.get_or_create(url='http://ggruiz.me/weeknd3/')
    bmID_139.save()
    bmID_139.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_152,bmID_b_152 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1345853')
    bmID_152.save()
    bmID_152.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_326,bmID_b_326 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/random-polygon-ellipse/')
    bmID_326.save()
    bmID_326.fname.add(f_Jason_Davies_James)
    bmID_301,bmID_b_301 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/calkin-wilf-tree/')
    bmID_301.save()
    bmID_301.fname.add(f_Jason_Davies_James)
    bmID_250,bmID_b_250 = Bookmark.objects.get_or_create(url='http://trisul.org/')
    bmID_250.save()
    bmID_250.fname.add(f_Products_Martyna)
    bmID_180,bmID_b_180 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2295155')
    bmID_180.save()
    bmID_180.fname.add(f_Useful_snippets_Jean)
    bmID_261,bmID_b_261 = Bookmark.objects.get_or_create(url='http://dimplejs.org/')
    bmID_261.save()
    bmID_261.fname.add(f_Libraries_Martyna)
    bmID_127,bmID_b_127 = Bookmark.objects.get_or_create(url='http://dyninc.github.com/d3-smokechart/')
    bmID_127.save()
    bmID_127.fname.add(f_Misc_Charts_Jean)
    bmID_83,bmID_b_83 = Bookmark.objects.get_or_create(url='http://xliberation.com/googlecharts/d3nodefocustagsite.html')
    bmID_83.save()
    bmID_83.fname.add(f_Force_Layout_Wen)
    bmID_299,bmID_b_299 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/sunflower-phyllotaxis/')
    bmID_299.save()
    bmID_299.fname.add(f_Jason_Davies_James)
    bmID_64,bmID_b_64 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1062383')
    bmID_64.save()
    bmID_64.fname.add(f_Force_Layout_Wen)
    bmID_93,bmID_b_93 = Bookmark.objects.get_or_create(url='http://www.christophermanning.org/projects/voronoi-diagram-with-force-directed-nodes-and-delaunay-links/')
    bmID_93.save()
    bmID_93.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_52,bmID_b_52 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3921009')
    bmID_52.save()
    bmID_52.fname.add(f_Parallel_Coordinates_Parallel_sets_and_Sankey_Gosel)
    bmID_327,bmID_b_327 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/tuebingen/')
    bmID_327.save()
    bmID_327.fname.add(f_Jason_Davies_James)
    bmID_49,bmID_b_49 = Bookmark.objects.get_or_create(url='http://benjiec.github.io/scatter-matrix/demo/demo.html')
    bmID_49.save()
    bmID_49.fname.add(f_Scatterplot_and_Bubble_chart_Gosel)
    bmID_219,bmID_b_219 = Bookmark.objects.get_or_create(url='http://webmonarch.github.com/d34raphael/usage.html')
    bmID_219.save()
    bmID_219.fname.add(f_Interoperability_Jean)
    bmID_88,bmID_b_88 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/999346')
    bmID_88.save()
    bmID_88.fname.add(f_Tree_Wen)
    bmID_181,bmID_b_181 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1343714')
    bmID_181.save()
    bmID_181.fname.add(f_Useful_snippets_Jean)
    bmID_226,bmID_b_226 = Bookmark.objects.get_or_create(url='http://briantford.com/blog/angular-d3.html')
    bmID_226.save()
    bmID_226.fname.add(f_Interoperability_Jean)
    bmID_274,bmID_b_274 = Bookmark.objects.get_or_create(url='http://www.jeromecukier.net/projects/models/ca.html')
    bmID_274.save()
    bmID_274.fname.add(f_Jerome_Cukier_Martyna)
    bmID_277,bmID_b_277 = Bookmark.objects.get_or_create(url='http://www.jeromecukier.net/projects/models/segregate.html')
    bmID_277.save()
    bmID_277.fname.add(f_Jerome_Cukier_Martyna)
    bmID_46,bmID_b_46 = Bookmark.objects.get_or_create(url='http://slodge.com/teach/')
    bmID_46.save()
    bmID_46.fname.add(f_Scatterplot_and_Bubble_chart_Gosel)
    bmID_284,bmID_b_284 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/bubbles/')
    bmID_284.save()
    bmID_284.fname.add(f_Jason_Davies_Martyna)
    bmID_148,bmID_b_148 = Bookmark.objects.get_or_create(url='http://vvvvjs.quasipartikel.at/')
    bmID_148.save()
    bmID_148.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_337,bmID_b_337 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/church_by_state.html')
    bmID_337.save()
    bmID_337.fname.add(f_Jim_Vallandingham_James)
    bmID_190,bmID_b_190 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3605124')
    bmID_190.save()
    bmID_190.fname.add(f_Useful_snippets_Jean)
    bmID_179,bmID_b_179 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1846692')
    bmID_179.save()
    bmID_179.fname.add(f_Useful_snippets_Jean)
    bmID_160,bmID_b_160 = Bookmark.objects.get_or_create(url='http://blog.latentflip.com/post/18195267992/d3-collider')
    bmID_160.save()
    bmID_160.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_108,bmID_b_108 = Bookmark.objects.get_or_create(url='http://fleetinbeing.net/d3e/chord.html')
    bmID_108.save()
    bmID_108.fname.add(f_Chord_Layout_Wen)
    bmID_287,bmID_b_287 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/plasma/')
    bmID_287.save()
    bmID_287.fname.add(f_Jason_Davies_Martyna)
    bmID_65,bmID_b_65 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1021841')
    bmID_65.save()
    bmID_65.fname.add(f_Force_Layout_Wen)
    bmID_15,bmID_b_15 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1283663')
    bmID_15.save()
    bmID_15.fname.add(f_Bar_Chart_Gosel)
    bmID_36,bmID_b_36 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1629644')
    bmID_36.save()
    bmID_36.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_244,bmID_b_244 = Bookmark.objects.get_or_create(url='https://bitdeli.com/')
    bmID_244.save()
    bmID_244.fname.add(f_Products_Martyna)
    bmID_285,bmID_b_285 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/set-partitions/')
    bmID_285.save()
    bmID_285.fname.add(f_Jason_Davies_Martyna)
    bmID_21,bmID_b_21 = Bookmark.objects.get_or_create(url='https://github.com/gencay/stackedGroupedChart')
    bmID_21.save()
    bmID_21.fname.add(f_Bar_Chart_Gosel)
    bmID_97,bmID_b_97 = Bookmark.objects.get_or_create(url='http://bit.ly/PvWgUH')
    bmID_97.save()
    bmID_97.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_188,bmID_b_188 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4053096')
    bmID_188.save()
    bmID_188.fname.add(f_Useful_snippets_Jean)
    bmID_281,bmID_b_281 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/maps/simplify/')
    bmID_281.save()
    bmID_281.fname.add(f_Jason_Davies_Martyna)
    bmID_328,bmID_b_328 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/american-forces-in-afghanistan-and-iraq/')
    bmID_328.save()
    bmID_328.fname.add(f_Jason_Davies_James)
    bmID_125,bmID_b_125 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1962173')
    bmID_125.save()
    bmID_125.fname.add(f_Misc_Charts_Jean)
    bmID_201,bmID_b_201 = Bookmark.objects.get_or_create(url='https://github.com/hhuuggoo/pushd3')
    bmID_201.save()
    bmID_201.fname.add(f_Interoperability_Jean)
    bmID_182,bmID_b_182 = Bookmark.objects.get_or_create(url='http://jsfiddle.net/7WQjr/')
    bmID_182.save()
    bmID_182.fname.add(f_Useful_snippets_Jean)
    bmID_138,bmID_b_138 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/849853')
    bmID_138.save()
    bmID_138.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_61,bmID_b_61 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1005873')
    bmID_61.save()
    bmID_61.fname.add(f_Sunburst_and_Partition_layout_Wen)
    bmID_294,bmID_b_294 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/bml/')
    bmID_294.save()
    bmID_294.fname.add(f_Jason_Davies_Martyna)
    bmID_234,bmID_b_234 = Bookmark.objects.get_or_create(url='http://ramblings.mcpher.com/Home/excelquirks/gassites/d3-concept-browser')
    bmID_234.save()
    bmID_234.fname.add(f_Interoperability_Jean)
    bmID_62,bmID_b_62 = Bookmark.objects.get_or_create(url='http://xliberation.com/parse/colortable/parsed3.html')
    bmID_62.save()
    bmID_62.fname.add(f_Sunburst_and_Partition_layout_Wen)
    bmID_162,bmID_b_162 = Bookmark.objects.get_or_create(url='http://markmarkoh.com/rhok')
    bmID_162.save()
    bmID_162.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_51,bmID_b_51 = Bookmark.objects.get_or_create(url='http://nickrabinowitz.com/projects/d3/alluvial/alluvial-dynamic.html')
    bmID_51.save()
    bmID_51.fname.add(f_Parallel_Coordinates_Parallel_sets_and_Sankey_Gosel)
    bmID_45,bmID_b_45 = Bookmark.objects.get_or_create(url='http://www.ericbullington.com/articles/2012/01/31/kmeans-visualization')
    bmID_45.save()
    bmID_45.fname.add(f_Scatterplot_and_Bubble_chart_Gosel)
    bmID_8,bmID_b_8 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/gbd/visualizations/gbd-arrow-diagram')
    bmID_8.save()
    bmID_8.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)
    bmID_31,bmID_b_31 = Bookmark.objects.get_or_create(url='http://benjchristensen.com/2011/08/08/simple-sparkline-using-svg-path-and-d3-js/')
    bmID_31.save()
    bmID_31.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_260,bmID_b_260 = Bookmark.objects.get_or_create(url='http://nvd3.org/')
    bmID_260.save()
    bmID_260.fname.add(f_Libraries_Martyna)
    bmID_222,bmID_b_222 = Bookmark.objects.get_or_create(url='http://css.dzone.com/articles/render-geographic-information')
    bmID_222.save()
    bmID_222.fname.add(f_Interoperability_Jean)
    bmID_37,bmID_b_37 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1314483')
    bmID_37.save()
    bmID_37.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_272,bmID_b_272 = Bookmark.objects.get_or_create(url='http://www.jeromecukier.net/projects/models/percolate.html')
    bmID_272.save()
    bmID_272.fname.add(f_Jerome_Cukier_Martyna)
    bmID_57,bmID_b_57 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4168921')
    bmID_57.save()
    bmID_57.fname.add(f_Parallel_Coordinates_Parallel_sets_and_Sankey_Gosel)
    bmID_177,bmID_b_177 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1367999')
    bmID_177.save()
    bmID_177.fname.add(f_Useful_snippets_Jean)
    bmID_189,bmID_b_189 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4047002')
    bmID_189.save()
    bmID_189.fname.add(f_Useful_snippets_Jean)
    bmID_338,bmID_b_338 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/nationality_by_city.html')
    bmID_338.save()
    bmID_338.fname.add(f_Jim_Vallandingham_James)
    bmID_84,bmID_b_84 = Bookmark.objects.get_or_create(url='http://blog.pixelingene.com/2011/07/building-a-tree-diagram-in-d3-js/')
    bmID_84.save()
    bmID_84.fname.add(f_Tree_Wen)
    bmID_130,bmID_b_130 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3543186')
    bmID_130.save()
    bmID_130.fname.add(f_Misc_Charts_Jean)
    bmID_257,bmID_b_257 = Bookmark.objects.get_or_create(url='http://mortgagebloom.com')
    bmID_257.save()
    bmID_257.fname.add(f_Products_Martyna)
    bmID_334,bmID_b_334 = Bookmark.objects.get_or_create(url='http://vallandingham.me/feltronifier/')
    bmID_334.save()
    bmID_334.fname.add(f_Jim_Vallandingham_James)
    bmID_78,bmID_b_78 = Bookmark.objects.get_or_create(url='http://www.christophermanning.org/projects/chicago-lobbyists-force-directed-graph-visualization/')
    bmID_78.save()
    bmID_78.fname.add(f_Force_Layout_Wen)
    bmID_43,bmID_b_43 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1346395')
    bmID_43.save()
    bmID_43.fname.add(f_Pie_Chart_Gosel)
    bmID_220,bmID_b_220 = Bookmark.objects.get_or_create(url='http://www.dotuscomus.com/pergola/pergola_1.4.0/ExamplesHTML/D3/multiD3.html')
    bmID_220.save()
    bmID_220.fname.add(f_Interoperability_Jean)
    bmID_119,bmID_b_119 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2206590')
    bmID_119.save()
    bmID_119.fname.add(f_Maps_Jean)
    bmID_236,bmID_b_236 = Bookmark.objects.get_or_create(url='http://www.bangongyun.com/chart')
    bmID_236.save()
    bmID_236.fname.add(f_Online_Editors_Jean)
    bmID_98,bmID_b_98 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/972398')
    bmID_98.save()
    bmID_98.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_143,bmID_b_143 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1123639')
    bmID_143.save()
    bmID_143.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_155,bmID_b_155 = Bookmark.objects.get_or_create(url='https://github.com/boorad/d3-tsline')
    bmID_155.save()
    bmID_155.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_60,bmID_b_60 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/coffee-wheel/')
    bmID_60.save()
    bmID_60.fname.add(f_Sunburst_and_Partition_layout_Wen)
    bmID_126,bmID_b_126 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2280295')
    bmID_126.save()
    bmID_126.fname.add(f_Misc_Charts_Jean)
    bmID_90,bmID_b_90 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1249394')
    bmID_90.save()
    bmID_90.fname.add(f_Tree_Wen)
    bmID_11,bmID_b_11 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/gbd/visualizations/gbd-2010-healthy-years-lost-vs-life-expectancy')
    bmID_11.save()
    bmID_11.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)
    bmID_80,bmID_b_80 = Bookmark.objects.get_or_create(url='http://pmsangal.tumblr.com/post/65499782255/visualizing-web-performance-1')
    bmID_80.save()
    bmID_80.fname.add(f_Force_Layout_Wen)
    bmID_110,bmID_b_110 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4062006')
    bmID_110.save()
    bmID_110.fname.add(f_Chord_Layout_Wen)
    bmID_118,bmID_b_118 = Bookmark.objects.get_or_create(url='http://nbremer.blogspot.nl/2014/02/switching-behavior-between-phone-brands.html')
    bmID_118.save()
    bmID_118.fname.add(f_Chord_Layout_Jean)
    bmID_300,bmID_b_300 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/girko-circle/')
    bmID_300.save()
    bmID_300.fname.add(f_Jason_Davies_James)
    bmID_167,bmID_b_167 = Bookmark.objects.get_or_create(url='http://exposedata.com/hypercube/rotate/')
    bmID_167.save()
    bmID_167.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_35,bmID_b_35 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1483226')
    bmID_35.save()
    bmID_35.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_66,bmID_b_66 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1021953')
    bmID_66.save()
    bmID_66.fname.add(f_Force_Layout_Wen)
    bmID_197,bmID_b_197 = Bookmark.objects.get_or_create(url='http://blogs.infoecho.net/echo/2012/02/05/ipython-notebook-d3-js-mashup/')
    bmID_197.save()
    bmID_197.fname.add(f_Interoperability_Jean)
    bmID_207,bmID_b_207 = Bookmark.objects.get_or_create(url='https://github.com/davidcox/plotsk')
    bmID_207.save()
    bmID_207.fname.add(f_Interoperability_Jean)
    bmID_215,bmID_b_215 = Bookmark.objects.get_or_create(url='http://exposedata.com/canvas/stacked.html')
    bmID_215.save()
    bmID_215.fname.add(f_Interoperability_Jean)
    bmID_340,bmID_b_340 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/matlab_license.html')
    bmID_340.save()
    bmID_340.fname.add(f_bin_James)
    bmID_289,bmID_b_289 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/crayola/')
    bmID_289.save()
    bmID_289.fname.add(f_Jason_Davies_Martyna)
    bmID_157,bmID_b_157 = Bookmark.objects.get_or_create(url='http://www.larsko.org/v/euc/')
    bmID_157.save()
    bmID_157.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_153,bmID_b_153 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1386444')
    bmID_153.save()
    bmID_153.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_102,bmID_b_102 = Bookmark.objects.get_or_create(url='http://www.tips-for-excel.com/MCFC/Passes.html')
    bmID_102.save()
    bmID_102.fname.add(f_Chord_Layout_Wen)
    bmID_305,bmID_b_305 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/17x17/')
    bmID_305.save()
    bmID_305.fname.add(f_Jason_Davies_James)
    bmID_16,bmID_b_16 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/882152')
    bmID_16.save()
    bmID_16.fname.add(f_Bar_Chart_Gosel)
    bmID_168,bmID_b_168 = Bookmark.objects.get_or_create(url='http://blog.lightjs.org/2012/10/welcome-to-webplatform-animation-d3js/')
    bmID_168.save()
    bmID_168.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_325,bmID_b_325 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/pythagoras-proof/')
    bmID_325.save()
    bmID_325.fname.add(f_Jason_Davies_James)
    bmID_331,bmID_b_331 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/gates/')
    bmID_331.save()
    bmID_331.fname.add(f_Jim_Vallandingham_James)
    bmID_38,bmID_b_38 = Bookmark.objects.get_or_create(url='http://tympanus.net/codrops/2012/08/29/multiple-area-charts-with-d3-js/')
    bmID_38.save()
    bmID_38.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_106,bmID_b_106 = Bookmark.objects.get_or_create(url='http://bost.ocks.org/mike/uberdata/')
    bmID_106.save()
    bmID_106.fname.add(f_Chord_Layout_Wen)
    bmID_94,bmID_b_94 = Bookmark.objects.get_or_create(url='http://www.christophermanning.org/projects/building-cubic-hamiltonian-graphs-from-lcf-notation/')
    bmID_94.save()
    bmID_94.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_203,bmID_b_203 = Bookmark.objects.get_or_create(url='http://drsm79.github.com/Backbone-d3/index.html')
    bmID_203.save()
    bmID_203.fname.add(f_Interoperability_Jean)
    bmID_173,bmID_b_173 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/nbremer/raw/6506614/')
    bmID_173.save()
    bmID_173.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_71,bmID_b_71 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1062288')
    bmID_71.save()
    bmID_71.fname.add(f_Force_Layout_Wen)
    bmID_332,bmID_b_332 = Bookmark.objects.get_or_create(url='http://stowers.org/stowersreport/maps')
    bmID_332.save()
    bmID_332.fname.add(f_Jim_Vallandingham_James)
    bmID_216,bmID_b_216 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1846692')
    bmID_216.save()
    bmID_216.fname.add(f_Interoperability_Jean)
    bmID_211,bmID_b_211 = Bookmark.objects.get_or_create(url='http://excelramblings.blogspot.co.uk/2012/07/visualizing-system-integrations-using.html')
    bmID_211.save()
    bmID_211.fname.add(f_Interoperability_Jean)
    bmID_55,bmID_b_55 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/parallel-sets/')
    bmID_55.save()
    bmID_55.fname.add(f_Parallel_Coordinates_Parallel_sets_and_Sankey_Gosel)
    bmID_123,bmID_b_123 = Bookmark.objects.get_or_create(url='http://tomerdoron.blogspot.com/2011/12/google-style-gauges-using-d3js.html')
    bmID_123.save()
    bmID_123.fname.add(f_Misc_Charts_Jean)
    bmID_288,bmID_b_288 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/random-arboretum/')
    bmID_288.save()
    bmID_288.fname.add(f_Jason_Davies_Martyna)
    bmID_158,bmID_b_158 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1629464')
    bmID_158.save()
    bmID_158.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_319,bmID_b_319 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/bifurcation/')
    bmID_319.save()
    bmID_319.fname.add(f_Jason_Davies_James)
    bmID_172,bmID_b_172 = Bookmark.objects.get_or_create(url='http://jklabz.com/d3/digital_clock/digital_clock.html')
    bmID_172.save()
    bmID_172.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_212,bmID_b_212 = Bookmark.objects.get_or_create(url='http://www.benh.co.uk/datasift/visualising-a-datasift-feed-with-node-and-d3/')
    bmID_212.save()
    bmID_212.fname.add(f_Interoperability_Jean)
    bmID_273,bmID_b_273 = Bookmark.objects.get_or_create(url='http://www.jeromecukier.net/projects/models/markov.html')
    bmID_273.save()
    bmID_273.fname.add(f_Jerome_Cukier_Martyna)
    bmID_141,bmID_b_141 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1086421')
    bmID_141.save()
    bmID_141.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_34,bmID_b_34 = Bookmark.objects.get_or_create(url='http://benjchristensen.com/2012/05/02/line-graphs-using-d3-js/')
    bmID_34.save()
    bmID_34.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_323,bmID_b_323 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/morley-triangle/')
    bmID_323.save()
    bmID_323.fname.add(f_Jason_Davies_James)
    bmID_237,bmID_b_237 = Bookmark.objects.get_or_create(url='http://livecoding.gabrielflor.it')
    bmID_237.save()
    bmID_237.fname.add(f_Online_Editors_Martyna)
    bmID_109,bmID_b_109 = Bookmark.objects.get_or_create(url='http://livecoding.io/3419309')
    bmID_109.save()
    bmID_109.fname.add(f_Chord_Layout_Wen)
    bmID_89,bmID_b_89 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1061834')
    bmID_89.save()
    bmID_89.fname.add(f_Tree_Wen)
    bmID_165,bmID_b_165 = Bookmark.objects.get_or_create(url='http://dan.iel.fm/xkcd/')
    bmID_165.save()
    bmID_165.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_44,bmID_b_44 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/4710330/94a7c0aeb6f09d681dbfdd0e5150578e4935c6ae')
    bmID_44.save()
    bmID_44.fname.add(f_Pie_Chart_Gosel)
    bmID_9,bmID_b_9 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/gbd/visualizations/gbd-uncertainty-visualization')
    bmID_9.save()
    bmID_9.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)
    bmID_79,bmID_b_79 = Bookmark.objects.get_or_create(url='http://fanfarefantastique.com/vishna/')
    bmID_79.save()
    bmID_79.fname.add(f_Force_Layout_Wen)
    bmID_303,bmID_b_303 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/carotid/')
    bmID_303.save()
    bmID_303.fname.add(f_Jason_Davies_James)
    bmID_309,bmID_b_309 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/hilbert-stocks/#GOOG,AAPL,ADBE,NTFL,AMZN,INTC,ARMH,A')
    bmID_309.save()
    bmID_309.fname.add(f_Jason_Davies_James)
    bmID_322,bmID_b_322 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/leibniz-spiral/')
    bmID_322.save()
    bmID_322.fname.add(f_Jason_Davies_James)
    bmID_311,bmID_b_311 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/gaussian-primes/')
    bmID_311.save()
    bmID_311.fname.add(f_Jason_Davies_James)
    bmID_32,bmID_b_32 = Bookmark.objects.get_or_create(url='http://benjchristensen.com/2012/05/15/interactive-line-graph-using-d3-js/')
    bmID_32.save()
    bmID_32.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_107,bmID_b_107 = Bookmark.objects.get_or_create(url='http://exposedata.com/tutorial/chord/latest.html')
    bmID_107.save()
    bmID_107.fname.add(f_Chord_Layout_Wen)
    bmID_29,bmID_b_29 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1166403')
    bmID_29.save()
    bmID_29.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_238,bmID_b_238 = Bookmark.objects.get_or_create(url='http://enjalot.com/tributary/2165875/sinwaves.js')
    bmID_238.save()
    bmID_238.fname.add(f_Online_Editors_Martyna)
    bmID_12,bmID_b_12 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/tools/data-visualization/life-expectancy-county-and-sex-us-country-comparison-global-1989-1999-2009')
    bmID_12.save()
    bmID_12.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)
    bmID_134,bmID_b_134 = Bookmark.objects.get_or_create(url='http://mohdaslam.com/lte-rrc-rlc-mac-visualization-using-bubble-pack-layout/')
    bmID_134.save()
    bmID_134.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_25,bmID_b_25 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1933560')
    bmID_25.save()
    bmID_25.fname.add(f_Histogram_Gosel)
    bmID_169,bmID_b_169 = Bookmark.objects.get_or_create(url='http://metro.ezyang.com/')
    bmID_169.save()
    bmID_169.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_10,bmID_b_10 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/gbd/visualizations/gbd-cause-patterns')
    bmID_10.save()
    bmID_10.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)
    bmID_256,bmID_b_256 = Bookmark.objects.get_or_create(url='https://www.moh.io/')
    bmID_256.save()
    bmID_256.fname.add(f_Products_Martyna)
    bmID_85,bmID_b_85 = Bookmark.objects.get_or_create(url='http://blog.pixelingene.com/2011/08/progressive-reveal-animations-in-svg-using-a-svgclippath/')
    bmID_85.save()
    bmID_85.fname.add(f_Tree_Wen)
    bmID_314,bmID_b_314 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/tree-of-life/')
    bmID_314.save()
    bmID_314.fname.add(f_Jason_Davies_James)
    bmID_48,bmID_b_48 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4481531')
    bmID_48.save()
    bmID_48.fname.add(f_Scatterplot_and_Bubble_chart_Gosel)
    bmID_159,bmID_b_159 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1706523')
    bmID_159.save()
    bmID_159.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_208,bmID_b_208 = Bookmark.objects.get_or_create(url='http://blog.nextgenetics.net/?e=7')
    bmID_208.save()
    bmID_208.fname.add(f_Interoperability_Jean)
    bmID_282,bmID_b_282 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/duplicates/')
    bmID_282.save()
    bmID_282.fname.add(f_Jason_Davies_Martyna)
    bmID_2,bmID_b_2 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/tools/data-visualization/us-health-map')
    bmID_2.save()
    bmID_2.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_156,bmID_b_156 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1405439')
    bmID_156.save()
    bmID_156.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_164,bmID_b_164 = Bookmark.objects.get_or_create(url='http://bollwyvl.github.com/blockd3/')
    bmID_164.save()
    bmID_164.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_339,bmID_b_339 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/jobs_by_state.html')
    bmID_339.save()
    bmID_339.fname.add(f_Jim_Vallandingham_James)
    bmID_149,bmID_b_149 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1243323')
    bmID_149.save()
    bmID_149.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_254,bmID_b_254 = Bookmark.objects.get_or_create(url='http://nodal.me/login')
    bmID_254.save()
    bmID_254.fname.add(f_Products_Martyna)
    bmID_77,bmID_b_77 = Bookmark.objects.get_or_create(url='http://www.torlaune.de/euro-2012/spieler-relationen/')
    bmID_77.save()
    bmID_77.fname.add(f_Force_Layout_Wen)
    bmID_82,bmID_b_82 = Bookmark.objects.get_or_create(url='http://disqus.com/gravity')
    bmID_82.save()
    bmID_82.fname.add(f_Force_Layout_Wen)
    bmID_209,bmID_b_209 = Bookmark.objects.get_or_create(url='http://ramblings.mcpher.com/Home/excelquirks/d3/anyforce')
    bmID_209.save()
    bmID_209.fname.add(f_Interoperability_Jean)
    bmID_50,bmID_b_50 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/llb4ll/8709363')
    bmID_50.save()
    bmID_50.fname.add(f_Scatterplot_and_Bubble_chart_Gosel)
    bmID_232,bmID_b_232 = Bookmark.objects.get_or_create(url='http://ramblings.mcpher.com/Home/excelquirks/gassites/d3nodefocus')
    bmID_232.save()
    bmID_232.fname.add(f_Interoperability_Jean)
    bmID_246,bmID_b_246 = Bookmark.objects.get_or_create(url='http://square.github.com/tesseract/')
    bmID_246.save()
    bmID_246.fname.add(f_Products_Martyna)
    bmID_67,bmID_b_67 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2920551')
    bmID_67.save()
    bmID_67.fname.add(f_Force_Layout_Wen)
    bmID_131,bmID_b_131 = Bookmark.objects.get_or_create(url='http://nbremer.blogspot.com/2013/07/self-organizing-maps-adding-boundaries.html')
    bmID_131.save()
    bmID_131.fname.add(f_Misc_Charts_Jean)
    bmID_81,bmID_b_81 = Bookmark.objects.get_or_create(url='http://fcc.github.io/calltraffic/traffic2011.html')
    bmID_81.save()
    bmID_81.fname.add(f_Force_Layout_Wen)
    bmID_336,bmID_b_336 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/racial_divide.html')
    bmID_336.save()
    bmID_336.fname.add(f_Jim_Vallandingham_James)
    bmID_53,bmID_b_53 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1341281')
    bmID_53.save()
    bmID_53.fname.add(f_Parallel_Coordinates_Parallel_sets_and_Sankey_Gosel)
    bmID_202,bmID_b_202 = Bookmark.objects.get_or_create(url='http://quasipartikel.at/2012/04/25/dancing-with-data/')
    bmID_202.save()
    bmID_202.fname.add(f_Interoperability_Jean)
    bmID_112,bmID_b_112 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/1046712')
    bmID_112.save()
    bmID_112.fname.add(f_Chord_Layout_Wen)
    bmID_291,bmID_b_291 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/rhodonea/')
    bmID_291.save()
    bmID_291.fname.add(f_Jason_Davies_Martyna)
    bmID_128,bmID_b_128 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/d/3779574/')
    bmID_128.save()
    bmID_128.fname.add(f_Misc_Charts_Jean)
    bmID_28,bmID_b_28 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1624660')
    bmID_28.save()
    bmID_28.fname.add(f_Histogram_Gosel)
    bmID_278,bmID_b_278 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/maps/antipodes/')
    bmID_278.save()
    bmID_278.fname.add(f_Jason_Davies_Martyna)
    bmID_233,bmID_b_233 = Bookmark.objects.get_or_create(url='http://ramblings.mcpher.com/Home/excelquirks/d3/flights')
    bmID_233.save()
    bmID_233.fname.add(f_Interoperability_Jean)
    bmID_330,bmID_b_330 = Bookmark.objects.get_or_create(url='http://vallandingham.me/bubble_cloud/')
    bmID_330.save()
    bmID_330.fname.add(f_Jim_Vallandingham_James)
    bmID_329,bmID_b_329 = Bookmark.objects.get_or_create(url='http://flowingdata.com/2012/08/02/how-to-make-an-interactive-network-visualization/')
    bmID_329.save()
    bmID_329.fname.add(f_Jim_Vallandingham_James)
    bmID_171,bmID_b_171 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4589092')
    bmID_171.save()
    bmID_171.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_298,bmID_b_298 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/mobile-lawsuits/')
    bmID_298.save()
    bmID_298.fname.add(f_Jason_Davies_James)
    bmID_4,bmID_b_4 = Bookmark.objects.get_or_create(url='http://viz.healthmetricsandevaluation.org/gbd-compare/')
    bmID_4.save()
    bmID_4.fname.add(f_Miscellaneous_visualizations_Gosel)
    bmID_176,bmID_b_176 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1503463')
    bmID_176.save()
    bmID_176.fname.add(f_Useful_snippets_Jean)
    bmID_224,bmID_b_224 = Bookmark.objects.get_or_create(url='http://maxdemarzi.com/2012/02/13/visualizing-a-network-with-cypher/')
    bmID_224.save()
    bmID_224.fname.add(f_Interoperability_Jean)
    bmID_306,bmID_b_306 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/animated-quasicrystals/')
    bmID_306.save()
    bmID_306.fname.add(f_Jason_Davies_James)
    bmID_205,bmID_b_205 = Bookmark.objects.get_or_create(url='https://bitbucket.org/davidagraf/dartsplaytree/src')
    bmID_205.save()
    bmID_205.fname.add(f_Interoperability_Jean)
    bmID_239,bmID_b_239 = Bookmark.objects.get_or_create(url='http://phrogz.net/JS/d3-playground/#BlankDefault')
    bmID_239.save()
    bmID_239.fname.add(f_Online_Editors_Martyna)
    bmID_5,bmID_b_5 = Bookmark.objects.get_or_create(url='http://viz.healthmetricsandevaluation.org/mortality/')
    bmID_5.save()
    bmID_5.fname.add(f_Miscellaneous_visualizations_Gosel)
    bmID_290,bmID_b_290 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/parallel-sets/')
    bmID_290.save()
    bmID_290.fname.add(f_Jason_Davies_Martyna)
    bmID_18,bmID_b_18 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1327441')
    bmID_18.save()
    bmID_18.fname.add(f_Bar_Chart_Gosel)
    bmID_39,bmID_b_39 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4175202')
    bmID_39.save()
    bmID_39.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_58,bmID_b_58 = Bookmark.objects.get_or_create(url='http://charts.graphicbaseball.com/parallelbatting')
    bmID_58.save()
    bmID_58.fname.add(f_Parallel_Coordinates_Parallel_sets_and_Sankey_Wen)
    bmID_41,bmID_b_41 = Bookmark.objects.get_or_create(url='https://github.com/gajus/pie-chart')
    bmID_41.save()
    bmID_41.fname.add(f_Pie_Chart_Gosel)
    bmID_245,bmID_b_245 = Bookmark.objects.get_or_create(url='http://square.github.com/cube/')
    bmID_245.save()
    bmID_245.fname.add(f_Products_Martyna)
    bmID_114,bmID_b_114 = Bookmark.objects.get_or_create(url='http://fleetinbeing.net/d3e/chord.html')
    bmID_114.save()
    bmID_114.fname.add(f_Chord_Layout_Jean)
    bmID_6,bmID_b_6 = Bookmark.objects.get_or_create(url='http://viz.healthmetricsandevaluation.org/cod/')
    bmID_6.save()
    bmID_6.fname.add(f_Miscellaneous_visualizations_Gosel)
    bmID_166,bmID_b_166 = Bookmark.objects.get_or_create(url='http://latentflip.github.com/violin/')
    bmID_166.save()
    bmID_166.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_86,bmID_b_86 = Bookmark.objects.get_or_create(url='http://jsfiddle.net/murray_3/5q62y/8/')
    bmID_86.save()
    bmID_86.fname.add(f_Tree_Wen)
    bmID_26,bmID_b_26 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3048450')
    bmID_26.save()
    bmID_26.fname.add(f_Histogram_Gosel)
    bmID_13,bmID_b_13 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/tools/data-visualization/development-assistance-health-health-focus-area-global-1990-2009-interactiv')
    bmID_13.save()
    bmID_13.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)
    bmID_69,bmID_b_69 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2883411')
    bmID_69.save()
    bmID_69.fname.add(f_Force_Layout_Wen)
    bmID_133,bmID_b_133 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1020902')
    bmID_133.save()
    bmID_133.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_192,bmID_b_192 = Bookmark.objects.get_or_create(url='http://jsfiddle.net/shawnbot/BJLe6/')
    bmID_192.save()
    bmID_192.fname.add(f_Useful_snippets_Jean)
    bmID_104,bmID_b_104 = Bookmark.objects.get_or_create(url='http://www.torre.nl/remittances/')
    bmID_104.save()
    bmID_104.fname.add(f_Chord_Layout_Wen)
    bmID_92,bmID_b_92 = Bookmark.objects.get_or_create(url='http://maxdemarzi.com/2012/03/08/connections-in-time/')
    bmID_92.save()
    bmID_92.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_42,bmID_b_42 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1305111')
    bmID_42.save()
    bmID_42.fname.add(f_Pie_Chart_Gosel)
    bmID_19,bmID_b_19 = Bookmark.objects.get_or_create(url='https://github.com/mlarocca/Dynamic-Charts')
    bmID_19.save()
    bmID_19.fname.add(f_Bar_Chart_Gosel)
    bmID_113,bmID_b_113 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/1308257')
    bmID_113.save()
    bmID_113.fname.add(f_Chord_Layout_Wen)
    bmID_129,bmID_b_129 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1044242')
    bmID_129.save()
    bmID_129.fname.add(f_Misc_Charts_Jean)
    bmID_235,bmID_b_235 = Bookmark.objects.get_or_create(url='http://www.d3-generator.com/')
    bmID_235.save()
    bmID_235.fname.add(f_Online_Editors_Jean)
    bmID_221,bmID_b_221 = Bookmark.objects.get_or_create(url='http://sammyd.github.com/blog/2012/09/16/visualising-conair-data-with-cubism-dot-js/')
    bmID_221.save()
    bmID_221.fname.add(f_Interoperability_Jean)
    bmID_342,bmID_b_342 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/matlab_license.html')
    bmID_342.save()
    bmID_342.fname.add(f_bin_Jean)
    bmID_304,bmID_b_304 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/coffee-wheel/')
    bmID_304.save()
    bmID_304.fname.add(f_Jason_Davies_James)
    bmID_280,bmID_b_280 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/maps/random-points/')
    bmID_280.save()
    bmID_280.fname.add(f_Jason_Davies_Martyna)
    bmID_270,bmID_b_270 = Bookmark.objects.get_or_create(url='http://iop.io/iopctrl')
    bmID_270.save()
    bmID_270.fname.add(f_Libraries_Martyna)
    bmID_193,bmID_b_193 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4236639')
    bmID_193.save()
    bmID_193.fname.add(f_Useful_snippets_Jean)
    bmID_302,bmID_b_302 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/bloomfilter/')
    bmID_302.save()
    bmID_302.fname.add(f_Jason_Davies_James)
    bmID_121,bmID_b_121 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1067616')
    bmID_121.save()
    bmID_121.fname.add(f_Misc_Charts_Jean)
    bmID_183,bmID_b_183 = Bookmark.objects.get_or_create(url='http://jsfiddle.net/shawnbot/BJLe6/')
    bmID_183.save()
    bmID_183.fname.add(f_Useful_snippets_Jean)
    bmID_231,bmID_b_231 = Bookmark.objects.get_or_create(url='http://ramblings.mcpher.com/Home/excelquirks/parse/d3parse')
    bmID_231.save()
    bmID_231.fname.add(f_Interoperability_Jean)
    bmID_252,bmID_b_252 = Bookmark.objects.get_or_create(url='http://meshu.io/')
    bmID_252.save()
    bmID_252.fname.add(f_Products_Martyna)
    bmID_100,bmID_b_100 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4092944')
    bmID_100.save()
    bmID_100.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_204,bmID_b_204 = Bookmark.objects.get_or_create(url='http://blog.ouseful.info/2012/05/11/viewing-openlearn-mindmaps-using-d3-js/')
    bmID_204.save()
    bmID_204.fname.add(f_Interoperability_Jean)
    bmID_1,bmID_b_1 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/tools/data-visualization/us-health-map')
    bmID_1.save()
    bmID_1.fname.add(f_Evaluation_Gosel)
    bmID_30,bmID_b_30 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1157787')
    bmID_30.save()
    bmID_30.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_247,bmID_b_247 = Bookmark.objects.get_or_create(url='http://polychart.com/')
    bmID_247.save()
    bmID_247.fname.add(f_Products_Martyna)
    bmID_91,bmID_b_91 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1093025')
    bmID_91.save()
    bmID_91.fname.add(f_Tree_Wen)
    bmID_137,bmID_b_137 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1117287')
    bmID_137.save()
    bmID_137.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_218,bmID_b_218 = Bookmark.objects.get_or_create(url='https://github.com/mhemesath/r2d3/')
    bmID_218.save()
    bmID_218.fname.add(f_Interoperability_Jean)
    bmID_33,bmID_b_33 = Bookmark.objects.get_or_create(url='http://mpf.vis.ywng.cloudbees.net/')
    bmID_33.save()
    bmID_33.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_210,bmID_b_210 = Bookmark.objects.get_or_create(url='http://blog.echen.me/2012/03/05/instant-interactive-visualization-with-d3-and-ggplot2/')
    bmID_210.save()
    bmID_210.fname.add(f_Interoperability_Jean)
    bmID_333,bmID_b_333 = Bookmark.objects.get_or_create(url='http://www.capitolmarkets.com/gsa-leased-investment-opportunity/')
    bmID_333.save()
    bmID_333.fname.add(f_Jim_Vallandingham_James)
    bmID_54,bmID_b_54 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3290263')
    bmID_54.save()
    bmID_54.fname.add(f_Parallel_Coordinates_Parallel_sets_and_Sankey_Gosel)
    bmID_313,bmID_b_313 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/earthquakes/#3.00/20.00/805.00')
    bmID_313.save()
    bmID_313.fname.add(f_Jason_Davies_James)
    bmID_276,bmID_b_276 = Bookmark.objects.get_or_create(url='http://www.jeromecukier.net/projects/models/polya.html')
    bmID_276.save()
    bmID_276.fname.add(f_Jerome_Cukier_Martyna)
    bmID_267,bmID_b_267 = Bookmark.objects.get_or_create(url='http://www.visualsedimentation.org/')
    bmID_267.save()
    bmID_267.fname.add(f_Libraries_Martyna)
    bmID_63,bmID_b_63 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/kerryrodden/7090426')
    bmID_63.save()
    bmID_63.fname.add(f_Sunburst_and_Partition_layout_Wen)
    bmID_316,bmID_b_316 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/animated-bezier/')
    bmID_316.save()
    bmID_316.fname.add(f_Jason_Davies_James)
    bmID_295,bmID_b_295 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/9patch/')
    bmID_295.save()
    bmID_295.fname.add(f_Jason_Davies_Martyna)
    bmID_217,bmID_b_217 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2294676')
    bmID_217.save()
    bmID_217.fname.add(f_Interoperability_Jean)
    bmID_292,bmID_b_292 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/wordcloud/#http%3A%2F%2Fsearch.twitter.com%2Fsearch.json%3Frpp%3D100%26q%3D%7Bword%7D=cloud')
    bmID_292.save()
    bmID_292.fname.add(f_Jason_Davies_Martyna)
    bmID_120,bmID_b_120 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1067636')
    bmID_120.save()
    bmID_120.fname.add(f_Misc_Charts_Jean)
    bmID_241,bmID_b_241 = Bookmark.objects.get_or_create(url='http://cssdeck.com/labs/d3-repulsive')
    bmID_241.save()
    bmID_241.fname.add(f_Online_Editors_Martyna)
    bmID_20,bmID_b_20 = Bookmark.objects.get_or_create(url='http://theoldbeggar.com/aid/')
    bmID_20.save()
    bmID_20.fname.add(f_Bar_Chart_Gosel)
    bmID_251,bmID_b_251 = Bookmark.objects.get_or_create(url='http://exploreanalytics.com/')
    bmID_251.save()
    bmID_251.fname.add(f_Products_Martyna)
    bmID_145,bmID_b_145 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1182434')
    bmID_145.save()
    bmID_145.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_283,bmID_b_283 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/factorisation-diagrams/')
    bmID_283.save()
    bmID_283.fname.add(f_Jason_Davies_Martyna)
    bmID_242,bmID_b_242 = Bookmark.objects.get_or_create(url='http://www.ubiq.co')
    bmID_242.save()
    bmID_242.fname.add(f_Products_Martyna)
    bmID_142,bmID_b_142 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1073373')
    bmID_142.save()
    bmID_142.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_105,bmID_b_105 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1046712')
    bmID_105.save()
    bmID_105.fname.add(f_Chord_Layout_Wen)
    bmID_0,bmID_b_0 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/tools/data-visualization/us-health-map')
    bmID_0.save()
    bmID_0.fname.add(f_Maps_Gosel)
    bmID_335,bmID_b_335 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/movie')
    bmID_335.save()
    bmID_335.fname.add(f_Jim_Vallandingham_James)
    bmID_341,bmID_b_341 = Bookmark.objects.get_or_create(url='http://vallandingham.me/vis/matlab_license.html')
    bmID_341.save()
    bmID_341.fname.add(f_bin_Wen)
    bmID_68,bmID_b_68 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/950642')
    bmID_68.save()
    bmID_68.fname.add(f_Force_Layout_Wen)
    bmID_243,bmID_b_243 = Bookmark.objects.get_or_create(url='https://www.droptask.com')
    bmID_243.save()
    bmID_243.fname.add(f_Products_Martyna)
    bmID_27,bmID_b_27 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3048166')
    bmID_27.save()
    bmID_27.fname.add(f_Histogram_Gosel)
    bmID_266,bmID_b_266 = Bookmark.objects.get_or_create(url='http://tenxer.github.com/xcharts/')
    bmID_266.save()
    bmID_266.fname.add(f_Libraries_Martyna)
    bmID_199,bmID_b_199 = Bookmark.objects.get_or_create(url='http://github.com/jakevdp/mpld3')
    bmID_199.save()
    bmID_199.fname.add(f_Interoperability_Jean)
    bmID_99,bmID_b_99 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4092944')
    bmID_99.save()
    bmID_99.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_17,bmID_b_17 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1134768')
    bmID_17.save()
    bmID_17.fname.add(f_Bar_Chart_Gosel)
    bmID_151,bmID_b_151 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1276463')
    bmID_151.save()
    bmID_151.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_154,bmID_b_154 = Bookmark.objects.get_or_create(url='https://github.com/enjalot/adventures_in_d3')
    bmID_154.save()
    bmID_154.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_23,bmID_b_23 = Bookmark.objects.get_or_create(url='https://github.com/liufly/Dual-scale-D3-Bar-Chart')
    bmID_23.save()
    bmID_23.fname.add(f_Bar_Chart_Gosel)
    bmID_264,bmID_b_264 = Bookmark.objects.get_or_create(url='https://github.com/shutterstock/rickshaw')
    bmID_264.save()
    bmID_264.fname.add(f_Libraries_Martyna)
    bmID_191,bmID_b_191 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3173233')
    bmID_191.save()
    bmID_191.fname.add(f_Useful_snippets_Jean)
    bmID_186,bmID_b_186 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3310323')
    bmID_186.save()
    bmID_186.fname.add(f_Useful_snippets_Jean)
    bmID_255,bmID_b_255 = Bookmark.objects.get_or_create(url='http://www.infocaptor.com')
    bmID_255.save()
    bmID_255.fname.add(f_Products_Martyna)
    bmID_248,bmID_b_248 = Bookmark.objects.get_or_create(url='http://plot.io/')
    bmID_248.save()
    bmID_248.fname.add(f_Products_Martyna)
    bmID_228,bmID_b_228 = Bookmark.objects.get_or_create(url='http://jllord.github.com/sheetsee.js/')
    bmID_228.save()
    bmID_228.fname.add(f_Interoperability_Jean)
    bmID_213,bmID_b_213 = Bookmark.objects.get_or_create(url='https://github.com/asutherland/d3-threeD')
    bmID_213.save()
    bmID_213.fname.add(f_Interoperability_Jean)
    bmID_230,bmID_b_230 = Bookmark.objects.get_or_create(url='http://dexvis.com')
    bmID_230.save()
    bmID_230.fname.add(f_Interoperability_Jean)
    bmID_214,bmID_b_214 = Bookmark.objects.get_or_create(url='http://jsfiddle.net/plaliberte/HAXyd/')
    bmID_214.save()
    bmID_214.fname.add(f_Interoperability_Jean)
    bmID_132,bmID_b_132 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1021103')
    bmID_132.save()
    bmID_132.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_3,bmID_b_3 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/tools/data-visualization/us-health-map')
    bmID_3.save()
    bmID_3.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)
    bmID_150,bmID_b_150 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1353700')
    bmID_150.save()
    bmID_150.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_96,bmID_b_96 = Bookmark.objects.get_or_create(url='http://blockses.appspot.com/2503502')
    bmID_96.save()
    bmID_96.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_259,bmID_b_259 = Bookmark.objects.get_or_create(url='http://nickqizhu.github.com/dc.js/')
    bmID_259.save()
    bmID_259.fname.add(f_Libraries_Martyna)
    bmID_194,bmID_b_194 = Bookmark.objects.get_or_create(url='http://ollieglass.com/2012/04/21/bieber-fever-meter-with-html5s-web-socket-d3-js-and-pusher/')
    bmID_194.save()
    bmID_194.fname.add(f_Useful_snippets_Jean)
    bmID_136,bmID_b_136 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1016220')
    bmID_136.save()
    bmID_136.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_184,bmID_b_184 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1691430')
    bmID_184.save()
    bmID_184.fname.add(f_Useful_snippets_Jean)
    bmID_87,bmID_b_87 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2966094')
    bmID_87.save()
    bmID_87.fname.add(f_Tree_Wen)
    bmID_76,bmID_b_76 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1377729')
    bmID_76.save()
    bmID_76.fname.add(f_Force_Layout_Wen)
    bmID_135,bmID_b_135 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1062544')
    bmID_135.save()
    bmID_135.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_101,bmID_b_101 = Bookmark.objects.get_or_create(url='http://jimkang.com/quadtreevis/')
    bmID_101.save()
    bmID_101.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_116,bmID_b_116 = Bookmark.objects.get_or_create(url='http://radialsets.org')
    bmID_116.save()
    bmID_116.fname.add(f_Chord_Layout_Jean)
    bmID_268,bmID_b_268 = Bookmark.objects.get_or_create(url='https://github.com/ignacioola/insights')
    bmID_268.save()
    bmID_268.fname.add(f_Libraries_Martyna)
    bmID_249,bmID_b_249 = Bookmark.objects.get_or_create(url='http://chart.io/')
    bmID_249.save()
    bmID_249.fname.add(f_Products_Martyna)
    bmID_279,bmID_b_279 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/maps/simplify/koch/')
    bmID_279.save()
    bmID_279.fname.add(f_Jason_Davies_Martyna)
    bmID_196,bmID_b_196 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4149176')
    bmID_196.save()
    bmID_196.fname.add(f_Useful_snippets_Jean)
    bmID_206,bmID_b_206 = Bookmark.objects.get_or_create(url='http://ramblings.mcpher.com/Home/excelquirks/d3/sankey')
    bmID_206.save()
    bmID_206.fname.add(f_Interoperability_Jean)
    bmID_297,bmID_b_297 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/planarity/')
    bmID_297.save()
    bmID_297.fname.add(f_Jason_Davies_James)
    bmID_56,bmID_b_56 = Bookmark.objects.get_or_create(url='http://www.theage.com.au/national/parsets')
    bmID_56.save()
    bmID_56.fname.add(f_Parallel_Coordinates_Parallel_sets_and_Sankey_Gosel)
    bmID_111,bmID_b_111 = Bookmark.objects.get_or_create(url='http://www.javainc.com/projects/dex/examples/vis/d3/presidents/presidentPartyChord.html')
    bmID_111.save()
    bmID_111.fname.add(f_Chord_Layout_Wen)
    bmID_7,bmID_b_7 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/gbd/visualizations/gbd-heatmap')
    bmID_7.save()
    bmID_7.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)
    bmID_225,bmID_b_225 = Bookmark.objects.get_or_create(url='https://github.com/hadley/r2d3')
    bmID_225.save()
    bmID_225.fname.add(f_Interoperability_Jean)
    bmID_324,bmID_b_324 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/poincare-disc/')
    bmID_324.save()
    bmID_324.fname.add(f_Jason_Davies_James)
    bmID_269,bmID_b_269 = Bookmark.objects.get_or_create(url='http://sepans.com/sp/postes/lepracursor/')
    bmID_269.save()
    bmID_269.fname.add(f_Libraries_Martyna)
    bmID_200,bmID_b_200 = Bookmark.objects.get_or_create(url='http://www.drewconway.com/zia/?p=2765')
    bmID_200.save()
    bmID_200.fname.add(f_Interoperability_Jean)
    bmID_258,bmID_b_258 = Bookmark.objects.get_or_create(url='http://apps.microsoft.com/windows/en-us/app/presentation-next/57c55802-1bdd-48c9-bf8b-e9e3c24cf051')
    bmID_258.save()
    bmID_258.fname.add(f_Store_Apps_Martyna)
    bmID_187,bmID_b_187 = Bookmark.objects.get_or_create(url='http://d3export.cancan.cshl.edu/')
    bmID_187.save()
    bmID_187.fname.add(f_Useful_snippets_Jean)
    bmID_315,bmID_b_315 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/voroboids/')
    bmID_315.save()
    bmID_315.fname.add(f_Jason_Davies_James)
    bmID_163,bmID_b_163 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/3287802')
    bmID_163.save()
    bmID_163.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_122,bmID_b_122 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1005090')
    bmID_122.save()
    bmID_122.fname.add(f_Misc_Charts_Jean)
    bmID_320,bmID_b_320 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/sorting/')
    bmID_320.save()
    bmID_320.fname.add(f_Jason_Davies_James)
    bmID_263,bmID_b_263 = Bookmark.objects.get_or_create(url='http://square.github.com/crossfilter/')
    bmID_263.save()
    bmID_263.fname.add(f_Libraries_Martyna)
    bmID_175,bmID_b_175 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1071269')
    bmID_175.save()
    bmID_175.fname.add(f_Useful_snippets_Jean)
    bmID_195,bmID_b_195 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/4246925')
    bmID_195.save()
    bmID_195.fname.add(f_Useful_snippets_Jean)
    bmID_75,bmID_b_75 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1129492')
    bmID_75.save()
    bmID_75.fname.add(f_Force_Layout_Wen)
    bmID_70,bmID_b_70 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/929623')
    bmID_70.save()
    bmID_70.fname.add(f_Force_Layout_Wen)
    bmID_161,bmID_b_161 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1552725')
    bmID_161.save()
    bmID_161.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_240,bmID_b_240 = Bookmark.objects.get_or_create(url='http://fleetinbeing.net/beans/d3')
    bmID_240.save()
    bmID_240.fname.add(f_Online_Editors_Martyna)
    bmID_308,bmID_b_308 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/hamming-quilt/')
    bmID_308.save()
    bmID_308.fname.add(f_Jason_Davies_James)
    bmID_229,bmID_b_229 = Bookmark.objects.get_or_create(url='http://timelyportfolio.blogspot.com/2012/12/d3-shiny-and-r-reporting-performance.html')
    bmID_229.save()
    bmID_229.fname.add(f_Interoperability_Jean)
    bmID_47,bmID_b_47 = Bookmark.objects.get_or_create(url='http://jsfiddle.net/indiemaps/gzPDU/')
    bmID_47.save()
    bmID_47.fname.add(f_Scatterplot_and_Bubble_chart_Gosel)
    bmID_253,bmID_b_253 = Bookmark.objects.get_or_create(url='http://www.simple.com/blog/Simple/announcing-reports')
    bmID_253.save()
    bmID_253.fname.add(f_Products_Martyna)
    bmID_73,bmID_b_73 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/2846454')
    bmID_73.save()
    bmID_73.fname.add(f_Force_Layout_Wen)
    bmID_74,bmID_b_74 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1153292')
    bmID_74.save()
    bmID_74.fname.add(f_Force_Layout_Wen)
    bmID_174,bmID_b_174 = Bookmark.objects.get_or_create(url='http://gist.github.com/plandem/5683951')
    bmID_174.save()
    bmID_174.fname.add(f_Useful_snippets_Jean)
    bmID_227,bmID_b_227 = Bookmark.objects.get_or_create(url='http://ramblings.mcpher.com/Home/excelquirks/d3/partition')
    bmID_227.save()
    bmID_227.fname.add(f_Interoperability_Jean)
    bmID_312,bmID_b_312 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/wave/')
    bmID_312.save()
    bmID_312.fname.add(f_Jason_Davies_James)
    bmID_307,bmID_b_307 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/collatz-graph/')
    bmID_307.save()
    bmID_307.fname.add(f_Jason_Davies_James)
    bmID_24,bmID_b_24 = Bookmark.objects.get_or_create(url='https://github.com/gajus/interdependent-interactive-histograms')
    bmID_24.save()
    bmID_24.fname.add(f_Histogram_Gosel)
    bmID_318,bmID_b_318 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/apollonian-gasket/')
    bmID_318.save()
    bmID_318.fname.add(f_Jason_Davies_James)
    bmID_262,bmID_b_262 = Bookmark.objects.get_or_create(url='http://square.github.com/cubism/')
    bmID_262.save()
    bmID_262.fname.add(f_Libraries_Martyna)
    bmID_95,bmID_b_95 = Bookmark.objects.get_or_create(url='http://thepowerrank.com/visual/NCAA_Tournament_Predictions')
    bmID_95.save()
    bmID_95.fname.add(f_Misc_Trees_and_Graphs_Wen)
    bmID_310,bmID_b_310 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/hilbert-curve/')
    bmID_310.save()
    bmID_310.fname.add(f_Jason_Davies_James)
    bmID_275,bmID_b_275 = Bookmark.objects.get_or_create(url='http://www.jeromecukier.net/projects/models/life.html')
    bmID_275.save()
    bmID_275.fname.add(f_Jerome_Cukier_Martyna)
    bmID_144,bmID_b_144 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1136236')
    bmID_144.save()
    bmID_144.fname.add(f_Miscellaneous_visualizations_Jean)
    bmID_198,bmID_b_198 = Bookmark.objects.get_or_create(url='https://github.com/mikedewar/d3py')
    bmID_198.save()
    bmID_198.fname.add(f_Interoperability_Jean)
    bmID_178,bmID_b_178 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/mbostock/1226718')
    bmID_178.save()
    bmID_178.fname.add(f_Useful_snippets_Jean)
    bmID_40,bmID_b_40 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/nswamy14/083a1e3181c81428f817')
    bmID_40.save()
    bmID_40.fname.add(f_Line_and_Area_Chart_Gosel)
    bmID_22,bmID_b_22 = Bookmark.objects.get_or_create(url='http://bl.ocks.org/rsloan/7123450')
    bmID_22.save()
    bmID_22.fname.add(f_Bar_Chart_Gosel)
    bmID_321,bmID_b_321 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/complete-graphs/')
    bmID_321.save()
    bmID_321.fname.add(f_Jason_Davies_James)
    bmID_293,bmID_b_293 = Bookmark.objects.get_or_create(url='http://www.jasondavies.com/necklaces/')
    bmID_293.save()
    bmID_293.fname.add(f_Jason_Davies_Martyna)
    bmID_14,bmID_b_14 = Bookmark.objects.get_or_create(url='http://www.healthmetricsandevaluation.org/tools/data-visualization/development-assistance-health-channel-assistance-global-1990-2011-interacti')
    bmID_14.save()
    bmID_14.fname.add(f_Institute_for_Health_Metrics_and_Evaluation_Gosel)

    #Bin Folders
    binID_0 = add_binfolder(busername_fk=Martyna)
    binID_1 = add_binfolder(busername_fk=James)
    binID_2 = add_binfolder(busername_fk=Jean)
    binID_3 = add_binfolder(busername_fk=Wen)
    binID_4 = add_binfolder(busername_fk=Gosel)

def add_bookmark(site, fname, saved_times=0):
    domain = getDomain(site)
    bm = Bookmark.objects.get_or_create(site=site, domain=domain, fname=fname, saved_times=saved_times)[0]
    return bm

def add_folder(foldername, fusername_fk):
    f = Folder.objects.get_or_create(foldername=foldername, fusername_fk=fusername_fk)[0]
    return f

def add_binfolder(busername_fk):
    bf = BinFolder.objects.get_or_create(busername_fk=busername_fk)[0]
    return bf

# Start execution here!
if __name__ == '__main__':
    print 'Starting DragonDrop population script...'
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dragondrop_proj.settings')
    from dragondrop.models import User, Bookmark, Folder, BinFolder 
    populate()
